--이벤트
SELECT N.DCT_CODE "할인코드",N.DCT_FRND "친구초대",N.REMPER_CODE "추천인 코드",M.ID"아이디" FROM EVENT N, MEMBER M WHERE N.ID=M.ID;

--회원관리
SELECT M.ID"아이디",SO_LOGIN "소셜 로그인",CERTIFY "이메일 인증" FROM MEMMGR E, MEMBER M WHERE E.ID=M.ID;

--설정
SELECT M.ID"아이디",T.QUALITY"화질",T.SUBTITLE"자막",T.DUBBING"더빙",T.WIFI"데이터 접속 방식",T.ABROAD"해외접속" FROM SETTING T, MEMBER M WHERE T.ID = M.ID; 

--회원
SELECT M.ID"아이디",M.PWD"비밀번호",M.BIRTH"생년월일",M.PAYDAY"정기결제일",M.REMPER_CODE"추천인 코드" FROM MEMBER M;

--마이페이지
SELECT M.ID"아이디",P.VID_REQUEST"작품 신청",P.DOWNLOAD"다운로드",P.HISTORY"다 본 작품",P.SERVICE"고객센터",P.HEART_LIST"찜 목록 확인",P.COMMUNITY"읏챠 커뮤니티 참여" FROM MYPAGE P, MEMBER M WHERE P.ID=M.ID;

--관리자
SELECT MONTH"기간",MONTH_SALES"월별매출" FROM MANAGE;

--질문게시판
SELECT Q.QNA_IDX"질문코드",M.ID"아이디",Q.QNA_TITLE"질문제목",Q.QNA_POST"질문내용",Q.QNA_DATE"작성일",Q.QNA_COMPLETE"답변여부" FROM QNABD Q, MEMBER M WHERE Q.ID=M.ID;

--결제
SELECT ID"아이디",P_INFOM"결제정보",P_DATE"시작일",P_END"종료일" FROM PAY;

--장르
SELECT B.G_CODE "장르코드",G_NAME"장르명" FROM GENRE B;

--주제
SELECT A.J_CODE"주제코드",A.J_NAME"주제명" FROM SUBJECT A;

--작품
SELECT C.V_CODE"작품코드",C.V_NAME"제목",C.DIR_NAME"감독",C.COU_NAME"제작국가",C.ACTOR_NAME"주연배우",C.RELEASE_DATE"개봉일",A.J_CODE"주제코드",B.G_CODE"장르코드" FROM VID C, SUBJECT A, GENRE B WHERE C.J_CODE= A.J_CODE AND C.G_CODE= B.G_CODE;

--스트리밍
SELECT S.V_CODE"작품코드",M.ID"아이디" ,V_DATE"시청일자",V_CONTINUE"이어보기" FROM STREAMING S, VID C, MEMBER M WHERE S.V_CODE=C.V_CODE AND S.ID=M.ID;

--리뷰
SELECT R.V_CODE"작품코드",R.V_REVIEW"리뷰내용",R.V_GRADE"평점",M.ID"아이디" FROM REVIEW R, MEMBER M WHERE R.ID=M.ID;
